-- ============================================================================
-- Uy-Laurio Legal Portal — Seed data for local testing
-- ----------------------------------------------------------------------------
-- Run AFTER all migrations. Creating an auth user triggers profile creation
-- (handle_new_user), and inserting a case triggers the checklist seeding plus
-- the automated notifications, so this file stays deliberately small.
--
-- Passwords: password123
-- ============================================================================

-- ─── 1. Accounts ────────────────────────────────────────────────────────────

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at
) values
('00000000-0000-0000-0000-000000000000', 'a0000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
 'admin@uy-laurio.ph', crypt('password123', gen_salt('bf')), now(),
 '{"provider":"email","providers":["email"]}', '{"full_name":"System Admin","phone":"09000000000"}', now(), now()),
('00000000-0000-0000-0000-000000000000', 'c1111111-1111-1111-1111-111111111111', 'authenticated', 'authenticated',
 'client1@example.com', crypt('password123', gen_salt('bf')), now(),
 '{"provider":"email","providers":["email"]}', '{"full_name":"Juan Dela Cruz","phone":"09171234567"}', now(), now()),
('00000000-0000-0000-0000-000000000000', 'c2222222-2222-2222-2222-222222222222', 'authenticated', 'authenticated',
 'client2@example.com', crypt('password123', gen_salt('bf')), now(),
 '{"provider":"email","providers":["email"]}', '{"full_name":"Maria Clara","phone":"09181234567"}', now(), now())
on conflict (id) do nothing;

update public.profiles
set role = 'admin'
where id = 'a0000000-0000-0000-0000-000000000000';

-- ─── 2. Cases (checklists are generated by the trigger) ─────────────────────

insert into public.cases (id, client_id, module, module_detail, status, phase, created_by) values
('ca5e0000-0000-0000-0000-000000000001', 'c1111111-1111-1111-1111-111111111111',
 'notarization', 'Deed of Absolute Sale Notarization', 'pending', 'Submitted',
 'c1111111-1111-1111-1111-111111111111'),
('ca5e0000-0000-0000-0000-000000000002', 'c2222222-2222-2222-2222-222222222222',
 'ejs', 'Extrajudicial Settlement with Sale', 'progress', 'In Progress',
 'c2222222-2222-2222-2222-222222222222')
on conflict (id) do nothing;

-- Assign the second case to the admin so assignment views have data.
update public.cases
set assigned_to = 'a0000000-0000-0000-0000-000000000000'
where id = 'ca5e0000-0000-0000-0000-000000000002';

-- ─── 3. Documents (linked to the first checklist item of each case) ─────────

insert into public.documents
  (id, case_id, owner_id, name, storage_path, size_bytes, mime_type, status, requirement_id)
select
  'd0c00000-0000-0000-0000-000000000001',
  'ca5e0000-0000-0000-0000-000000000001',
  'c1111111-1111-1111-1111-111111111111',
  'valid_id_front.pdf',
  'c1111111-1111-1111-1111-111111111111/ca5e0000-0000-0000-0000-000000000001/valid_id_front.pdf',
  102400, 'application/pdf', 'pending',
  (select id from public.case_requirements
    where case_id = 'ca5e0000-0000-0000-0000-000000000001'
    order by sort_order limit 1)
on conflict (id) do nothing;

insert into public.documents
  (id, case_id, owner_id, name, storage_path, size_bytes, mime_type, status, requirement_id)
select
  'd0c00000-0000-0000-0000-000000000002',
  'ca5e0000-0000-0000-0000-000000000002',
  'c2222222-2222-2222-2222-222222222222',
  'death_certificate.jpg',
  'c2222222-2222-2222-2222-222222222222/ca5e0000-0000-0000-0000-000000000002/death_certificate.jpg',
  204800, 'image/jpeg', 'pending',
  (select id from public.case_requirements
    where case_id = 'ca5e0000-0000-0000-0000-000000000002'
    order by sort_order limit 1)
on conflict (id) do nothing;

-- ─── 4. Schedule overrides (holiday / half-day / custom hours) ──────────────

insert into public.schedule_overrides (override_date, type, open_time, close_time, created_by)
select d.override_date, d.type, d.open_time, d.close_time, 'a0000000-0000-0000-0000-000000000000'
from (values
  (current_date + 5, 'closed'::override_type,  null::text, null::text),
  (current_date + 6, 'halfday'::override_type, null,       null),
  (current_date + 7, 'custom'::override_type,  '10:00',    '15:00')
) as d(override_date, type, open_time, close_time)
on conflict (override_date) do nothing;

-- ─── 5. Appointments ───────────────────────────────────────────────────────
-- Slot labels must exist in office_time_slots and the date must be a day the
-- office is open, otherwise validate_appointment() rejects the row.

insert into public.appointments (client_id, appointment_date, time_slot, case_id)
select 'c1111111-1111-1111-1111-111111111111', d, '10:00 AM',
       'ca5e0000-0000-0000-0000-000000000001'
from (
  select min(day)::date as d
  from generate_series(current_date + 1, current_date + 10, interval '1 day') as day
  where extract(dow from day) between 1 and 6
    and not exists (
      select 1 from public.schedule_overrides o
      where o.override_date = day::date and o.type = 'closed'
    )
) pick
where d is not null;

insert into public.appointments (client_id, appointment_date, time_slot, case_id)
select 'c2222222-2222-2222-2222-222222222222', d, '2:00 PM',
       'ca5e0000-0000-0000-0000-000000000002'
from (
  select max(day)::date as d
  from generate_series(current_date + 1, current_date + 4, interval '1 day') as day
  where extract(dow from day) between 1 and 6
    and not exists (
      select 1 from public.schedule_overrides o
      where o.override_date = day::date and o.type in ('closed', 'halfday')
    )
) pick
where d is not null;

-- ─── 6. Notification history (delivery already confirmed) ──────────────────
-- The triggers already queued acknowledgements for the cases above; this row
-- shows what a delivered message looks like in the dispatch log.

insert into public.notifications
  (case_id, recipient_id, recipient, channel, message, kind, status, delivery_status, sent_at, created_by)
values
('ca5e0000-0000-0000-0000-000000000001', 'c1111111-1111-1111-1111-111111111111',
 'client1@example.com', 'email',
 'Your case for Notarization has been received. We will notify you once review begins.',
 'manual', 'confirmed', 'sent', now(), 'a0000000-0000-0000-0000-000000000000');
